import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790114062692 implements MigrationInterface {
    name = 'InitialSchema1790114062692'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS postgis`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "workflow_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "version" integer NOT NULL DEFAULT '1', "taskTypes" text array NOT NULL DEFAULT '{}', "isDefault" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "initialState" character varying NOT NULL, "states" jsonb NOT NULL, "transitions" jsonb NOT NULL, CONSTRAINT "PK_4f92fadfc5fb722f080ceaec272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04ba9a1546aa90eb39497739ab" ON "workflow_definitions" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_258b4826057fd60448715ef0ba" ON "workflow_definitions" ("organizationId", "code", "version") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'AGENT', 'CLIENT', 'DIRECTION')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INVITED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."users_mfachannel_enum" AS ENUM('EMAIL', 'SMS')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying, "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "mfaEnabled" boolean NOT NULL DEFAULT false, "mfaChannel" "public"."users_mfachannel_enum" NOT NULL DEFAULT 'EMAIL', "clientId" uuid, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3d6aea8fcca58182b2e80ce97" ON "users" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c3a73bbc9d8a8082816adc870" ON "users" ("clientId") `);
        await queryRunner.query(`CREATE TABLE "sites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "clientId" uuid NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL, "postalCode" character varying, "city" character varying, "location" geography(Point,4326), "geofenceMeters" integer, "zoneId" uuid, "contactName" character varying, "contactPhone" character varying, "accessInstructions" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4f5eccb1dfde10c9170502595a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_adb9781864a04730f7223964cc" ON "sites" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_848fd46b5b68d16657c944f7bc" ON "sites" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1516efb8cd9a59205e85a1a9a9" ON "sites" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying NOT NULL, "code" character varying NOT NULL, "email" character varying, "phone" character varying, "billingAddress" character varying, "contractReference" character varying, "isActive" boolean NOT NULL DEFAULT true, "notes" text, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d3cec4a5221398155c784ff78" ON "clients" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b44cbe8c8db040c1bb956648f0" ON "clients" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "reference" character varying NOT NULL, "title" character varying NOT NULL, "description" text, "type" character varying NOT NULL, "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'NORMAL', "status" character varying NOT NULL, "workflowId" uuid NOT NULL, "clientId" uuid NOT NULL, "siteId" uuid NOT NULL, "agentId" uuid, "createdById" uuid NOT NULL, "requiredSkills" text array NOT NULL DEFAULT '{}', "checklist" jsonb NOT NULL DEFAULT '[]', "parentTaskId" uuid, "scheduledStart" TIMESTAMP WITH TIME ZONE, "scheduledEnd" TIMESTAMP WITH TIME ZONE, "estimatedDurationMin" integer, "plannedAt" TIMESTAMP WITH TIME ZONE, "assignedAt" TIMESTAMP WITH TIME ZONE, "acceptedAt" TIMESTAMP WITH TIME ZONE, "enRouteAt" TIMESTAMP WITH TIME ZONE, "arrivedAt" TIMESTAMP WITH TIME ZONE, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "evaluatedAt" TIMESTAMP WITH TIME ZONE, "cancelledAt" TIMESTAMP WITH TIME ZONE, "slaPolicyId" uuid, "ackDueAt" TIMESTAMP WITH TIME ZONE, "arrivalDueAt" TIMESTAMP WITH TIME ZONE, "interventionDueAt" TIMESTAMP WITH TIME ZONE, "closeDueAt" TIMESTAMP WITH TIME ZONE, "ackBreached" boolean NOT NULL DEFAULT false, "arrivalBreached" boolean NOT NULL DEFAULT false, "interventionBreached" boolean NOT NULL DEFAULT false, "closeBreached" boolean NOT NULL DEFAULT false, "slaAlertsSent" text array NOT NULL DEFAULT '{}', "completionNotes" text, "signatureKey" character varying, "signedByName" character varying, "version" integer NOT NULL, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a9a5a9fada64fc56e2aaf2f946" ON "tasks" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a43b29dfedb5fce6199328bba8" ON "tasks" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e7cd3aff0dbd7708e02b14ecb" ON "tasks" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ffb8b08db07f8191fac41aea5" ON "tasks" ("siteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c0ccd52b3cc81959f6f603f1f" ON "tasks" ("scheduledStart") `);
        await queryRunner.query(`CREATE INDEX "IDX_07f3fd1a7d3b4b516a9325e595" ON "tasks" ("ackDueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6447a104d6b23072215d56cd7d" ON "tasks" ("closeDueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1aab4021a75a13751961491ae" ON "tasks" ("organizationId", "agentId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa206b1f0cc61f4426d7e93450" ON "tasks" ("organizationId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_379c7ba8e03069817c2ec2dc5c" ON "tasks" ("organizationId", "reference") `);
        await queryRunner.query(`CREATE TYPE "public"."sync_operations_status_enum" AS ENUM('APPLIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "sync_operations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "clientOpId" character varying NOT NULL, "type" character varying NOT NULL, "status" "public"."sync_operations_status_enum" NOT NULL, "result" jsonb, "clientTimestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "processedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2d303195599690ecfcd3343de8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c66bfbcb9a2ddde222635119d4" ON "sync_operations" ("userId", "clientOpId") `);
        await queryRunner.query(`CREATE TYPE "public"."task_events_source_enum" AS ENUM('ONLINE', 'OFFLINE_SYNC', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "task_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "taskId" uuid NOT NULL, "type" character varying NOT NULL, "fromStatus" character varying, "toStatus" character varying, "actorId" uuid, "comment" text, "data" jsonb, "location" geography(Point,4326), "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "source" "public"."task_events_source_enum" NOT NULL DEFAULT 'ONLINE', CONSTRAINT "PK_5ad150da47d65e2346ff40169cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d41b066a642d09f9fa6c2c4f17" ON "task_events" ("taskId", "recordedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."sla_policies_priority_enum" AS ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TABLE "sla_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying NOT NULL, "clientId" uuid, "siteId" uuid, "taskType" character varying, "priority" "public"."sla_policies_priority_enum", "acknowledgeMinutes" integer, "arrivalMinutes" integer, "interventionMinutes" integer, "closureMinutes" integer, "warningMinutesBefore" integer NOT NULL DEFAULT '15', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_41b6803cef982534243a67b6302" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8180674b393d8734a0b1fd0792" ON "sla_policies" ("organizationId") `);
        await queryRunner.query(`CREATE TYPE "public"."photos_type_enum" AS ENUM('BEFORE', 'AFTER', 'PROOF', 'SIGNATURE', 'DOCUMENT', 'ANOMALY')`);
        await queryRunner.query(`CREATE TYPE "public"."photos_validation_enum" AS ENUM('PENDING', 'VALIDATED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "taskId" uuid NOT NULL, "type" "public"."photos_type_enum" NOT NULL, "storageKey" character varying NOT NULL, "contentType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "sha256" character varying NOT NULL, "location" geography(Point,4326), "accuracyMeters" real, "takenAt" TIMESTAMP WITH TIME ZONE NOT NULL, "uploadedById" uuid NOT NULL, "clientPhotoId" character varying, "caption" text, "validation" "public"."photos_validation_enum" NOT NULL DEFAULT 'PENDING', "validatedById" uuid, "validatedAt" TIMESTAMP WITH TIME ZONE, "rejectionReason" text, CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d56f3a34a6591f074756e66218" ON "photos" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bc15155e27c2500f03de5424a" ON "photos" ("taskId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2611db0c1874da8e773e89fdd6" ON "photos" ("uploadedById", "clientPhotoId") WHERE "clientPhotoId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying NOT NULL, "code" character varying NOT NULL, "description" character varying, "area" geography(Polygon,4326), CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bbdd14f8b36385ef988d09b12c" ON "zones" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8c6c2c74f9145e9bc153658a3b" ON "zones" ("organizationId", "code") `);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "name" character varying NOT NULL, "supervisorId" uuid, "zoneId" uuid, CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_858389ddeb0bd6c6bf4e323f91" ON "teams" ("organizationId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('PUSH', 'EMAIL', 'SMS', 'IN_APP')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'READ')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "data" jsonb, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'PENDING', "attempts" integer NOT NULL DEFAULT '0', "lastError" text, "sentAt" TIMESTAMP WITH TIME ZONE, "readAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_928914a0743f50e6f83a90cdda" ON "notifications" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "settings" jsonb NOT NULL DEFAULT '{"timezone":"Europe/Paris","locationIntervalSec":30,"trackingOnlyOnDuty":true,"photoRetentionDays":365,"locationRetentionDays":90,"defaultGeofenceMeters":300,"mfaRequiredRoles":[]}', "taskSeq" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_963693341bd612aa01ddf3a4b6" ON "organizations" ("slug") `);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "token" character varying NOT NULL, "platform" character varying NOT NULL, "lastSeenAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a059627f5d20f0b3cfdcdde542" ON "device_tokens" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_511957e3e8443429dc3fb00120" ON "device_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_977e24c520c49436d08e5eeea8" ON "device_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "location_pings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "agentId" uuid NOT NULL, "location" geography(Point,4326) NOT NULL, "accuracy" real, "speed" real, "heading" real, "battery" real, "taskId" uuid, "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "receivedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b666c5c0408c8bd318811640532" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddf03f37c8de270ed0d0d0d7de" ON "location_pings" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_f963b3451154c64d25b1a58d9a" ON "location_pings" ("organizationId", "recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_93c2c9dccf6e786f0bde7f7325" ON "location_pings" ("agentId", "recordedAt") `);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "taskId" uuid NOT NULL, "agentId" uuid, "authorId" uuid NOT NULL, "rating" integer NOT NULL, "punctualityRating" integer, "qualityRating" integer, "comment" text, CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eac7a33defa31b9ba1f4a155c3" ON "evaluations" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ecb4630d4d12861f3e190f336f" ON "evaluations" ("taskId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdf73968b6c7bb612050ee261e" ON "evaluations" ("agentId") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "familyId" uuid NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "usedAt" TIMESTAMP WITH TIME ZONE, "userAgent" character varying, "ip" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_40e9a8b923a1b3fb4429a5c624" ON "refresh_tokens" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid, "userId" uuid, "action" character varying NOT NULL, "resource" character varying NOT NULL, "resourceId" character varying, "details" jsonb, "ip" character varying, "userAgent" character varying, "success" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5db7a2b9e2bd2563b2377c293c" ON "audit_logs" ("resource", "resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9885c0f9a2e4081ebae4313d87" ON "audit_logs" ("organizationId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."agent_profiles_status_enum" AS ENUM('PENDING_VALIDATION', 'ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "agent_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "activityType" character varying NOT NULL DEFAULT 'MAINTENANCE', "skills" text array NOT NULL DEFAULT '{}', "zoneId" uuid, "teamId" uuid, "status" "public"."agent_profiles_status_enum" NOT NULL DEFAULT 'PENDING_VALIDATION', "validatedById" uuid, "validatedAt" TIMESTAMP WITH TIME ZONE, "isOnDuty" boolean NOT NULL DEFAULT false, "dutyStartedAt" TIMESTAMP WITH TIME ZONE, "availability" jsonb NOT NULL DEFAULT '{}', "maxConcurrentTasks" integer NOT NULL DEFAULT '5', "qualityScore" numeric(5,2), "vehicle" character varying, CONSTRAINT "REL_b33e9dd5843a6c76a1123463bc" UNIQUE ("userId"), CONSTRAINT "PK_4583ee140a2222f8fcecf3ac023" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df974ea5b39f01a5781e485a70" ON "agent_profiles" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b33e9dd5843a6c76a1123463bc" ON "agent_profiles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d7f274de98a76ad38ed479acc" ON "agent_profiles" ("zoneId") `);
        await queryRunner.query(`ALTER TABLE "sites" ADD CONSTRAINT "FK_848fd46b5b68d16657c944f7bc6" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_59b2c33d2a8cbfe6a2e6bc942ed" FOREIGN KEY ("workflowId") REFERENCES "workflow_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_4e7cd3aff0dbd7708e02b14ecb8" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_4ffb8b08db07f8191fac41aea5b" FOREIGN KEY ("siteId") REFERENCES "sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_1725c01e2d8e86b7f4f32ac8933" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_profiles" ADD CONSTRAINT "FK_b33e9dd5843a6c76a1123463bc1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "agent_profiles" DROP CONSTRAINT "FK_b33e9dd5843a6c76a1123463bc1"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_1725c01e2d8e86b7f4f32ac8933"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_4ffb8b08db07f8191fac41aea5b"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_4e7cd3aff0dbd7708e02b14ecb8"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_59b2c33d2a8cbfe6a2e6bc942ed"`);
        await queryRunner.query(`ALTER TABLE "sites" DROP CONSTRAINT "FK_848fd46b5b68d16657c944f7bc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d7f274de98a76ad38ed479acc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b33e9dd5843a6c76a1123463bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df974ea5b39f01a5781e485a70"`);
        await queryRunner.query(`DROP TABLE "agent_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."agent_profiles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9885c0f9a2e4081ebae4313d87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5db7a2b9e2bd2563b2377c293c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40e9a8b923a1b3fb4429a5c624"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdf73968b6c7bb612050ee261e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecb4630d4d12861f3e190f336f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eac7a33defa31b9ba1f4a155c3"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93c2c9dccf6e786f0bde7f7325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f963b3451154c64d25b1a58d9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddf03f37c8de270ed0d0d0d7de"`);
        await queryRunner.query(`DROP TABLE "location_pings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_977e24c520c49436d08e5eeea8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_511957e3e8443429dc3fb00120"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a059627f5d20f0b3cfdcdde542"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_963693341bd612aa01ddf3a4b6"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_928914a0743f50e6f83a90cdda"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_858389ddeb0bd6c6bf4e323f91"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c6c2c74f9145e9bc153658a3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbdd14f8b36385ef988d09b12c"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2611db0c1874da8e773e89fdd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bc15155e27c2500f03de5424a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d56f3a34a6591f074756e66218"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP TYPE "public"."photos_validation_enum"`);
        await queryRunner.query(`DROP TYPE "public"."photos_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8180674b393d8734a0b1fd0792"`);
        await queryRunner.query(`DROP TABLE "sla_policies"`);
        await queryRunner.query(`DROP TYPE "public"."sla_policies_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d41b066a642d09f9fa6c2c4f17"`);
        await queryRunner.query(`DROP TABLE "task_events"`);
        await queryRunner.query(`DROP TYPE "public"."task_events_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c66bfbcb9a2ddde222635119d4"`);
        await queryRunner.query(`DROP TABLE "sync_operations"`);
        await queryRunner.query(`DROP TYPE "public"."sync_operations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_379c7ba8e03069817c2ec2dc5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa206b1f0cc61f4426d7e93450"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1aab4021a75a13751961491ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6447a104d6b23072215d56cd7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07f3fd1a7d3b4b516a9325e595"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c0ccd52b3cc81959f6f603f1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ffb8b08db07f8191fac41aea5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e7cd3aff0dbd7708e02b14ecb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a43b29dfedb5fce6199328bba8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9a5a9fada64fc56e2aaf2f946"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b44cbe8c8db040c1bb956648f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d3cec4a5221398155c784ff78"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1516efb8cd9a59205e85a1a9a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_848fd46b5b68d16657c944f7bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_adb9781864a04730f7223964cc"`);
        await queryRunner.query(`DROP TABLE "sites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c3a73bbc9d8a8082816adc870"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3d6aea8fcca58182b2e80ce97"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_mfachannel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_258b4826057fd60448715ef0ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04ba9a1546aa90eb39497739ab"`);
        await queryRunner.query(`DROP TABLE "workflow_definitions"`);
    }

}
