import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'tasks',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'reference', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'workflow_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'client_json', type: 'string' },
        { name: 'site_id', type: 'string' },
        { name: 'site_json', type: 'string' },
        { name: 'agent_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'checklist_json', type: 'string' },
        { name: 'scheduled_start', type: 'number', isOptional: true },
        { name: 'scheduled_end', type: 'number', isOptional: true },
        { name: 'milestones_json', type: 'string' },
        { name: 'sla_json', type: 'string' },
        { name: 'completion_notes', type: 'string', isOptional: true },
        { name: 'signature_key', type: 'string', isOptional: true },
        { name: 'signed_by_name', type: 'string', isOptional: true },
        { name: 'photo_counts_json', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'server_updated_at', type: 'number' },
        { name: 'local_status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'task_notes_pending',
      columns: [
        { name: 'task_server_id', type: 'string', isIndexed: true },
        { name: 'text', type: 'string' },
        { name: 'client_op_id', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'pending_operations',
      columns: [
        { name: 'client_op_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'task_server_id', type: 'string', isIndexed: true },
        { name: 'client_timestamp', type: 'number' },
        { name: 'payload_json', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'error_json', type: 'string', isOptional: true },
        { name: 'attempts', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'photos_queue',
      columns: [
        { name: 'local_uri', type: 'string' },
        { name: 'client_photo_id', type: 'string', isIndexed: true },
        { name: 'task_server_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'lat', type: 'number', isOptional: true },
        { name: 'lng', type: 'number', isOptional: true },
        { name: 'accuracy', type: 'number', isOptional: true },
        { name: 'taken_at', type: 'number' },
        { name: 'caption', type: 'string', isOptional: true },
        { name: 'signed_by_name', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'attempts', type: 'number' },
        { name: 'error', type: 'string', isOptional: true },
        { name: 'server_photo_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'workflows',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'definition_json', type: 'string' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'location_pings',
      columns: [
        { name: 'lat', type: 'number' },
        { name: 'lng', type: 'number' },
        { name: 'accuracy', type: 'number', isOptional: true },
        { name: 'speed', type: 'number', isOptional: true },
        { name: 'heading', type: 'number', isOptional: true },
        { name: 'battery', type: 'number', isOptional: true },
        { name: 'task_id', type: 'string', isOptional: true },
        { name: 'recorded_at', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'sync_meta',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
      ],
    }),
  ],
});
